# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: backtesting.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x62\x61\x63ktesting.proto\x12\x0b\x62\x61\x63ktesting\"s\n\x06\x43\x61ndle\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x0c\n\x04open\x18\x03 \x01(\x01\x12\x0c\n\x04high\x18\x04 \x01(\x01\x12\x0b\n\x03low\x18\x05 \x01(\x01\x12\r\n\x05\x63lose\x18\x06 \x01(\x01\x12\x0e\n\x06volume\x18\x07 \x01(\x01\"\xad\x02\n\x05Order\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x16\n\x0eprecio_entrada\x18\x02 \x01(\x01\x12\x10\n\x08\x63\x61ntidad\x18\x03 \x01(\x01\x12\x11\n\tstop_loss\x18\x04 \x01(\x01\x12\x13\n\x0btake_profit\x18\x05 \x01(\x01\x12\x11\n\ttimestamp\x18\x06 \x01(\t\x12\x1b\n\x13\x65strategias_activas\x18\x07 \x01(\t\x12\x11\n\ttendencia\x18\x08 \x01(\t\x12\x11\n\tmax_price\x18\t \x01(\x01\x12\x11\n\tdireccion\x18\n \x01(\t\x12\x15\n\rprecio_cierre\x18\x0b \x01(\x01\x12\x14\n\x0c\x66\x65\x63ha_cierre\x18\x0c \x01(\t\x12\x15\n\rmotivo_cierre\x18\r \x01(\t\x12\x15\n\rretorno_total\x18\x0e \x01(\x01\"8\n\x0f\x42\x61\x63ktestRequest\x12\x0f\n\x07symbols\x18\x01 \x03(\t\x12\x14\n\x0c\x64\x61taset_path\x18\x02 \x01(\t\"\'\n\x10\x42\x61\x63ktestResponse\x12\x13\n\x0bjson_result\x18\x01 \x01(\t2]\n\x0f\x42\x61\x63ktestService\x12J\n\x0bRunBacktest\x12\x1c.backtesting.BacktestRequest\x1a\x1d.backtesting.BacktestResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'backtesting_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CANDLE']._serialized_start=34
  _globals['_CANDLE']._serialized_end=149
  _globals['_ORDER']._serialized_start=152
  _globals['_ORDER']._serialized_end=453
  _globals['_BACKTESTREQUEST']._serialized_start=455
  _globals['_BACKTESTREQUEST']._serialized_end=511
  _globals['_BACKTESTRESPONSE']._serialized_start=513
  _globals['_BACKTESTRESPONSE']._serialized_end=552
  _globals['_BACKTESTSERVICE']._serialized_start=554
  _globals['_BACKTESTSERVICE']._serialized_end=647
# @@protoc_insertion_point(module_scope)