# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orders.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0corders.proto\x12\x06worker\"\xad\x02\n\x05Order\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x16\n\x0eprecio_entrada\x18\x02 \x01(\x01\x12\x10\n\x08\x63\x61ntidad\x18\x03 \x01(\x01\x12\x11\n\tstop_loss\x18\x04 \x01(\x01\x12\x13\n\x0btake_profit\x18\x05 \x01(\x01\x12\x11\n\ttimestamp\x18\x06 \x01(\t\x12\x1b\n\x13\x65strategias_activas\x18\x07 \x01(\t\x12\x11\n\ttendencia\x18\x08 \x01(\t\x12\x11\n\tmax_price\x18\t \x01(\x01\x12\x11\n\tdireccion\x18\n \x01(\t\x12\x15\n\rprecio_cierre\x18\x0b \x01(\x01\x12\x14\n\x0c\x66\x65\x63ha_cierre\x18\x0c \x01(\t\x12\x15\n\rmotivo_cierre\x18\r \x01(\t\x12\x15\n\rretorno_total\x18\x0e \x01(\x01\",\n\x0bOrdersBatch\x12\x1d\n\x06orders\x18\x01 \x03(\x0b\x32\r.worker.Order\"\x1b\n\rWriteResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x32H\n\x0bOrderWriter\x12\x39\n\x0bWriteOrders\x12\x13.worker.OrdersBatch\x1a\x15.worker.WriteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orders_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDER']._serialized_start=25
  _globals['_ORDER']._serialized_end=326
  _globals['_ORDERSBATCH']._serialized_start=328
  _globals['_ORDERSBATCH']._serialized_end=372
  _globals['_WRITERESPONSE']._serialized_start=374
  _globals['_WRITERESPONSE']._serialized_end=401
  _globals['_ORDERWRITER']._serialized_start=403
  _globals['_ORDERWRITER']._serialized_end=475
# @@protoc_insertion_point(module_scope)