# core/procesar_vela.py — fachada estable (parches de métricas: ``core.vela.pipeline``)
"""Pipeline de velas cerradas: delega en :mod:`core.vela.pipeline`.

La lógica vive en ``core/vela/pipeline.py`` para reducir el tamaño del módulo
público y permitir evolucionar la implementación sin romper imports existentes.
"""
from __future__ import annotations

from core.vela.pipeline import (  # noqa: F401
    DEFAULT_MIN_BARS,
    BUFFER_SIZE_V2,
    BufferManager,
    CANDLES_IGNORADAS,
    CANDLES_PROCESSED_TOTAL,
    ENTRADAS_ABIERTAS,
    ENTRADAS_CANDIDATAS,
    ENTRADAS_RECHAZADAS_V2,
    EVAL_INTENTOS_TOTAL,
    EVAL_LATENCY,
    GATING_LATENCY,
    HANDLER_EXCEPTIONS,
    LAST_BAR_AGE,
    OrderCircuitBreakerOpen,
    OrderCircuitBreakerStore,
    PARSE_LATENCY,
    SPREAD_GUARD_ERRORS,
    SPREAD_GUARD_MISSING,
    STRATEGY_LATENCY,
    WARMUP_RESTANTE,
    _DEFAULT_ORDER_CIRCUIT_STORE,
    _ORDER_CIRCUIT_MAX_FAILURES,
    _ORDER_CREATION_MAX_ATTEMPTS,
    _abrir_orden,
    _buffers,
    _resolve_entrada_cooldown_tras_crear_failed_sec,
    create_buffer_manager,
    get_buffer_manager,
    procesar_vela,
    spread_gate_default,
)

__all__ = [
    "DEFAULT_MIN_BARS",
    "BUFFER_SIZE_V2",
    "BufferManager",
    "CANDLES_IGNORADAS",
    "CANDLES_PROCESSED_TOTAL",
    "ENTRADAS_ABIERTAS",
    "ENTRADAS_CANDIDATAS",
    "ENTRADAS_RECHAZADAS_V2",
    "EVAL_INTENTOS_TOTAL",
    "EVAL_LATENCY",
    "GATING_LATENCY",
    "HANDLER_EXCEPTIONS",
    "LAST_BAR_AGE",
    "OrderCircuitBreakerOpen",
    "OrderCircuitBreakerStore",
    "PARSE_LATENCY",
    "SPREAD_GUARD_ERRORS",
    "SPREAD_GUARD_MISSING",
    "STRATEGY_LATENCY",
    "WARMUP_RESTANTE",
    "_DEFAULT_ORDER_CIRCUIT_STORE",
    "_ORDER_CIRCUIT_MAX_FAILURES",
    "_ORDER_CREATION_MAX_ATTEMPTS",
    "_abrir_orden",
    "_buffers",
    "_resolve_entrada_cooldown_tras_crear_failed_sec",
    "create_buffer_manager",
    "get_buffer_manager",
    "procesar_vela",
    "spread_gate_default",
]
